package com.linxi.shop.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "customer")
public class Customer {
	
	  // ------------------------
	  // PRIVATE FIELDS
	  // ------------------------
	  
	  // An autogenerated id (unique for each user in the db)
//	  @Id
//	  @GeneratedValue(strategy = GenerationType.AUTO)
//	  private long id;
	  
	  @Id
	  @GeneratedValue(strategy = GenerationType.AUTO)
	  @Column(name="customerid")	  
	  private Long customerid;
	  
	  @NotNull
	  @Column(name = "userid")
	  private Long userid;
	  
	  @NotNull
	  @Column(name = "firstname")
	  private String firstname;
	  
	  @NotNull
	  @Column(name = "lastname")
	  private String lastname;
	  
	  @NotNull
	  @Column(name = "email")
	  private String email;
	  
	  @NotNull
	  @Column(name = "gender")
	  private String gender;
	  
	  @NotNull
	  @Column(name = "location")
	  private String location;
	
	  @NotNull
	  @Column(name = "status")
	  private String status;
	
	  @NotNull
	  @Column(name = "type")
	  private String type;
	
	  @NotNull
	  @Column(name = "description")
	  private String description;
	  
	  

	public Customer() {
		super();
	}
	
	public Customer(long customerid) {
		this.customerid = customerid;
	}

	public Customer(Long customerid, String firstname, String lastname, String email, String gender,
			String location, String status, String type, String description) {
		super();
		this.customerid = customerid;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.gender = gender;
		this.location = location;
		this.status = status;
		this.type = type;
		this.description = description;
	}

	public Long getCustomerid() {
		return customerid;
	}

	public void setCustomerid(Long customerid) {
		this.customerid = customerid;
	}

	public Long getUserid() {
		return userid;
	}

	public void setUserid(Long userid) {
		this.userid = userid;
	}

	public String getFirstname() {
		return firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	
  
} // class User
